### ISSUE TITLE
Rebooting when applying Easy list removal

### ISSUE THREAD

**Issue by gchamon** [AlexQuiniou/remove-bloatware-galaxy-s10e#1]
I have applied the `Easy list removal` and have been experiencing constant reboots.

I have reinstalled everything and played around with the package groups. I left `ANT +`, `Samsung partner`, `LED Cover` and `Lateral panel` intact and haven't seen reboot problems in the last hour or so.

Lateral Panel is the only one I think I use fairly often, the others I just narrowed down and didn't touch since getting a stable boot.

Just thought you might want to know.

**Comment by alex-quiniou** [comment]
Ok
