### ISSUE TITLE
A few additions

### ISSUE THREAD

**Issue by Sudrien** [AlexQuiniou/remove-bloatware-galaxy-s10e#2]
com.samsung.android.ipsgeofence
- "Samsung Visit in", add a banner add notification when it things you are near a samsung store

com.samsung.android.livestickers
- "DECO PIC" 

com.samsung.android.fast
- "Secure Wi-fi", limited VPN offering

com.samsung.android.mobileservice
- "Group Sharing"

**Comment by alex-quiniou** [comment]
Thanks for the help 😀
