### ISSUE TITLE
Don't uninstall com.samsung.android.honeyboard if you want to keep Accessibility

### ISSUE THREAD

**Issue by julian-alarcon** [AlexQuiniou/remove-bloatware-galaxy-s10e#5]
I found, after updating to Android 12 that the Accessibility setting needs this app, that was not the case before.
Tested in S21. Please look for other information on the Internet with the same finding.

**Comment by alex-quiniou** [comment]
I don't have android 12. Still using android 11 and galaxy S10e.
I publishing you finding in the readme
